# Generated by Django 6.0.4 on 2026-05-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0003_profile_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birthday',
        ),
    ]
