# Generated by Django 6.0.4 on 2026-05-02 20:04

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=Users.models.generate_name, max_length=25),
        ),
    ]
