# Generated by Django 6.0.4 on 2026-05-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='chat_icons/'),
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.CharField(default='Chat', max_length=50),
        ),
    ]
