# Generated by Django 6.0.4 on 2026-05-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
