# Generated by Django 6.0.4 on 2026-05-04 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_chat_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(related_name='admin_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
