# Generated by Django 6.0.4 on 2026-05-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_chat_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
