# Generated by Django 6.0.4 on 2026-05-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_message_if_system_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='pinned_messages',
            field=models.ManyToManyField(blank=True, null=True, related_name='pinned_in_chat', to='Main.message'),
        ),
    ]
