# Generated by Django 6.0.4 on 2026-05-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_chat_pinned_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='pinned_messages',
            field=models.ManyToManyField(blank=True, related_name='pinned_in_chat', to='Main.message'),
        ),
    ]
