# Generated by Django 6.0.4 on 2026-05-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_message_reply_to'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
