# Generated by Django 6.0.4 on 2026-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0016_remove_poll_is_multiple_choice_poll_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
