# Generated by Django 6.0.4 on 2026-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0017_alter_poll_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
